<?php
/**
 * 
 */
namespace FishPig\Util\Console\Command\Media\Image;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use FishPig\Util\Model\Media\Image\Cleaner\ImageCleanerInterface;

class CleanCommand extends \FishPig\Util\Console\Command\AbstractCommand
{
    /**
     * 
     */
    private const DRY_RUN = ImageCleanerInterface::DRY_RUN;
    private const ALL = 'all';
    private const PRODUCT = 'product';
    private const PRODUCT_AUTO_GENERATED = 'product-auto-generated';
    private const FISHPIG_WEBP = 'fishpig-webp';

    /**
     * 
     */
    public function __construct(
        private \FishPig\Util\Model\Media\Image\Cleaner\Product $productImageCleaner,
        private \FishPig\Util\Model\Media\Image\Cleaner\ProductAutoGenerated $productAutoGeneratedImageCleaner,
        private \FishPig\Util\Model\Media\Image\Cleaner\FishPigWebp $fishpigWebpImageCleaner,
        ?string $name = null
    ) {
        parent::__construct($name);
    }

    /**
     * 
     */
    protected function configure()
    {
        $this->setName('media:image:clean')
            ->setDescription('Prune unused images from the filesystem');

        $this->addOption(
            self::DRY_RUN,
            null,
            InputOption::VALUE_NONE,
            'Extra param required to allow delete SQL query'
        );
        $this->addOption(
            self::ALL,
            null,
            InputOption::VALUE_NONE,
            'Process all image types'
        );
        $this->addOption(
            self::PRODUCT,
            null,
            InputOption::VALUE_NONE,
            'Process product images'
        );
        $this->addOption(
            self::PRODUCT_AUTO_GENERATED,
            null,
            InputOption::VALUE_NONE,
            'Process product auto-generated images'
        );
        $this->addOption(
            self::FISHPIG_WEBP,
            null,
            InputOption::VALUE_NONE,
            'Process FishPig WebP images'
        );
        return parent::configure();
    }

    /**
     * 
     */
    public function execute(InputInterface $input, OutputInterface $output): int
    {
        $processAll = $input->getOption(self::ALL);

        if ($processAll || $input->getOption(self::PRODUCT)) {
            $this->productImageCleaner->process($input, $output);
        }

        if ($processAll || $input->getOption(self::PRODUCT_AUTO_GENERATED)) {
            $this->productAutoGeneratedImageCleaner->process($input, $output);
        }

        if ($processAll || $input->getOption(self::FISHPIG_WEBP)) {
            $this->fishpigWebpImageCleaner->process($input, $output);
        }

        return Command::SUCCESS;
    }
}