<?php
/**
 * 
 */
namespace FishPig\Util\Model\Media\Image\Cleaner;

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ProductAutoGenerated extends AbstractCleaner
{
    /**
     * 
     */
    public function process(InputInterface $input, OutputInterface $output): void
    {
        return;
        $basePath = BP . '/pub/media/catalog/product/cache';
        $dryRun = $input->getOption(ImageCleanerInterface::DRY_RUN);

        $this->recursiveScanDir(
            $basePath,
            function ($file) use ($output, $dryRun) {
                $originalFile = preg_replace('/cache\/[a-f0-9]{32}\//', '', $file);

                if (is_file($originalFile)) {
                    return;
                }

                $output->writeLn($file);

                if (!$dryRun) {
                    $this->unlink($file);
                }
            }
        );
    }
}
