<?php
/**
 * 
 */
namespace FishPig\Util\Model\Media\Image\Cleaner;

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ProductAutoGenerated extends AbstractCleaner
{
    /**
     * 
     */
    public function process(InputInterface $input, OutputInterface $output): void
    {
        $basePath = BP . '/pub/media/catalog/product/cache';

        $this->recursiveScanDir(
            $basePath,
            function ($file) use ($input, $output) {
                $originalFile = preg_replace('/cache\/[a-f0-9]{32}\//', '', $file);

                if (is_file($originalFile)) {
                    $this->keepFile($input, $output, $file);
                    return;
                }

                $this->removeFile($input, $output, $file);
            }
        );
    }
}
